### Listar donos
GET http://127.0.0.1:5000/donos


### Buscar dono
GET http://127.0.0.1:5000/donos/1


### Criar dono
POST http://127.0.0.1:5000/donos
Content-Type: application/json

{
    "nome": "Carlos Silva",
    "telefone": "45999999999"
}


### Atualizar dono
PUT http://127.0.0.1:5000/donos/1
Content-Type: application/json

{
    "nome": "Ana Paula Atualizada",
    "telefone": "45988888888"
}


### Remover dono
DELETE http://127.0.0.1:5000/donos/1


### Listar todos os pets
GET http://127.0.0.1:5000/pets


### Filtrar pets por dono
GET http://127.0.0.1:5000/pets?dono_id=1


### Buscar pet
GET http://127.0.0.1:5000/pets/1


### Criar pet
POST http://127.0.0.1:5000/pets
Content-Type: application/json

{
    "nome": "Bidu",
    "especie": "cachorro",
    "idade": 2,
    "dono_id": 1
}


### Testar dono inexistente
POST http://127.0.0.1:5000/pets
Content-Type: application/json

{
    "nome": "Bidu",
    "especie": "cachorro",
    "idade": 2,
    "dono_id": 999
}


### Atualizar pet
PUT http://127.0.0.1:5000/pets/1
Content-Type: application/json

{
    "nome": "Rex Atualizado",
    "especie": "cachorro",
    "idade": 5,
    "dono_id": 1
}


### Remover pet
DELETE http://127.0.0.1:5000/pets/1